# Generated by Django 3.2.6 on 2021-08-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='News',
        ),
    ]
