# Generated by Django 3.2.6 on 2021-08-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0003_news_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descriptions',
            new_name='content',
        ),
    ]
