# Generated by Django 3.2.6 on 2021-09-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0007_auto_20210905_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at']},
        ),
    ]
