# Generated by Django 3.2.7 on 2021-09-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
    ]
